import { defineConfig, devices } from '@playwright/test';

const PORT = Number(process.env.E2E_PORT ?? 4173);
const BASE_URL = `http://localhost:${PORT}/GameMasterEncounterMapBuilder/`;

/**
 * Playwright runs against the production build served by `vite preview`.
 * Using the preview server (not the dev server) means the URLs and asset
 * paths exactly mirror what GitHub Pages serves, including the
 * `/GameMasterEncounterMapBuilder/` base path.
 */
export default defineConfig({
  testDir: './e2e',
  testMatch: /.*\.spec\.ts$/,
  // Phase 61.2: pre-seed `onboardingComplete: true` in localStorage
  // so the tour doesn't auto-show in non-tour specs (where its dim
  // backdrop would block clicks on the canvas / context menu items).
  // The onboarding-tour spec clears the pref via `addInitScript` to
  // exercise the auto-show path explicitly.
  globalSetup: './e2e/global-setup.ts',
  timeout: 30_000,
  expect: { timeout: 5_000 },
  fullyParallel: true,
  forbidOnly: !!process.env.CI,
  retries: process.env.CI ? 2 : 0,
  workers: process.env.CI ? 1 : undefined,
  // HTML reporter on CI so the `Upload Playwright report` artifact step
  // has something to archive (otherwise the step warns "no files found").
  // `open: 'never'` keeps the default `playwright show-report` behavior
  // from trying to auto-open the report in a browser on the CI runner.
  reporter: process.env.CI
    ? [['github'], ['list'], ['html', { outputFolder: 'playwright-report', open: 'never' }]]
    : [['list']],
  use: {
    baseURL: BASE_URL,
    trace: 'retain-on-failure',
    screenshot: 'only-on-failure',
    video: 'off',
    // Generated by `globalSetup` above. Per-spec `addInitScript`
    // calls run AFTER the storage state is applied, so specs can
    // still override the seed (e.g. the onboarding-tour spec
    // removes the prefs key to trigger first-launch auto-show).
    storageState: 'playwright/.auth/storage-state.json',
  },
  projects: [
    {
      name: 'chromium',
      use: { ...devices['Desktop Chrome'] },
    },
  ],
  webServer: {
    command: `npm run build && npm run preview -- --port ${PORT} --strictPort`,
    url: BASE_URL,
    reuseExistingServer: !process.env.CI,
    timeout: 120_000,
    stdout: 'pipe',
    stderr: 'pipe',
  },
});
