/**
 * Phase 120 — player-proposed annotations.
 *
 * Spectators can suggest a map annotation (a labeled marker at a
 * world point) — the GM sees the suggestion in a side panel and
 * decides whether to APPROVE (which adds it as a real shared
 * `Annotation` patch) or DISMISS (drops the suggestion, no state
 * mutation).
 *
 * Why a proposal queue instead of letting Spectators write to state
 * directly? Authoritative state belongs to the GM in this app's
 * sync model — Phase 54 annotations, Phase 56 walls, Phase 50 HP,
 * etc. all flow GM → everyone. Spectators have read-only state +
 * fire-and-forget channels (chat, dice, pings). Annotations are
 * persistent + visible to every player, so they stay in the
 * GM-mediated path: Spectator suggests, GM approves.
 *
 * In-memory ring buffer per tab session — no localStorage. The GM
 * reads the queue while the panel is open; on tab close the queue
 * evaporates (matching combat log + chat behavior). Cap is small
 * (`DEFAULT_MAX_ENTRIES = 50`) — a session that accumulates 50
 * unapproved suggestions has bigger problems than a queue overflow.
 *
 * Pure module — no DOM. The panel UI calls `add` / `entries` /
 * `remove` / `clear` / `subscribe`.
 */

export interface AnnotationProposal {
  /** Stable id; generated by the sender so receivers can dedupe. */
  id: string;
  /** Originating tab's playerId (Phase 110 stable id). */
  senderId: string;
  /** Display name at moment of send. */
  senderName: string;
  /** World x coordinate of the proposed annotation. */
  x: number;
  /** World y coordinate of the proposed annotation. */
  y: number;
  /** Proposed annotation text. */
  text: string;
  /** Proposed marker color (typically the spectator's identity color). */
  color: string;
  /** ms since epoch at send time. */
  timestamp: number;
}

export interface AnnotationProposalsOptions {
  maxEntries?: number;
}

export interface AnnotationProposals {
  add(proposal: AnnotationProposal): void;
  entries(): AnnotationProposal[];
  size(): number;
  remove(id: string): void;
  clear(): void;
  subscribe(listener: () => void): () => void;
}

const DEFAULT_MAX_ENTRIES = 50;

export function createAnnotationProposals(
  opts: AnnotationProposalsOptions = {},
): AnnotationProposals {
  const maxEntries = opts.maxEntries ?? DEFAULT_MAX_ENTRIES;
  const buffer: AnnotationProposal[] = [];
  const listeners = new Set<() => void>();
  // Dedupe set sized to track the buffer; eviction (cap or remove)
  // frees the slot so a sender that recycles ids isn't permanently
  // blocked.
  const seenIds = new Set<string>();

  function notify() {
    for (const l of listeners) l();
  }

  return {
    add(proposal) {
      if (!proposal.id || seenIds.has(proposal.id)) return;
      seenIds.add(proposal.id);
      buffer.push(proposal);
      while (buffer.length > maxEntries) {
        const evicted = buffer.shift();
        if (evicted) seenIds.delete(evicted.id);
      }
      notify();
    },
    entries() {
      return buffer.slice();
    },
    size: () => buffer.length,
    remove(id: string) {
      const idx = buffer.findIndex((p) => p.id === id);
      if (idx < 0) return;
      buffer.splice(idx, 1);
      seenIds.delete(id);
      notify();
    },
    clear() {
      if (buffer.length === 0) return;
      buffer.length = 0;
      seenIds.clear();
      notify();
    },
    subscribe(listener) {
      listeners.add(listener);
      return () => listeners.delete(listener);
    },
  };
}
