/**
 * Phase 119 — player chat history.
 *
 * In-memory ring buffer per tab session — chat is fire-and-forget by
 * design (no localStorage persistence), matching the combat log
 * (Phase 94) pattern. On reload the panel starts empty + sees only
 * messages that arrive after that moment. Capped at
 * `DEFAULT_MAX_ENTRIES = 200` so a long session doesn't grow the
 * panel unboundedly.
 *
 * Messages flow over the existing sync channel (Phase 66 envelope);
 * each tab's own send goes through the local `add()` first so the
 * sender sees their message immediately + receivers see it on the
 * BroadcastChannel hop.
 *
 * Visibility:
 *   - `'shared'` — everyone sees + displays the message.
 *   - `'gm-only'` — Spectator-side filter drops these on receive so
 *     they don't render. Spectator → GM whisper IS allowed (sender
 *     is the Spectator; GM sees it; OTHER spectators filter it out).
 *     This is good-faith only — a tampered Spectator build could
 *     read GM-only messages off the wire. A future server-mediated
 *     architecture could enforce strictly, but that's out of scope
 *     for the local-first sync model.
 *
 * Pure module — no DOM. The panel UI calls `add` / `entries` /
 * `subscribe` / `clear`.
 */

export type ChatVisibility = 'shared' | 'gm-only';
export type ChatRole = 'gm' | 'spectator';

export interface ChatMessage {
  /** Stable id; generated by the sender so receivers can dedupe. */
  id: string;
  /** Originating tab's playerId (Phase 110 stable id). */
  senderId: string;
  /** Display name at the moment of send. */
  senderName: string;
  /** Originating role (drives "GM said:" vs "Player said:" UI). */
  senderRole: ChatRole;
  /** The message body. Plain text — no markdown / HTML by design. */
  text: string;
  /** Phase 119 — `shared` (default) or `gm-only` (Spectators drop on receive). */
  visibility: ChatVisibility;
  /** ms since epoch at send time. Monotonic per-sender; cross-tab clocks may differ. */
  timestamp: number;
}

export interface ChatHistoryOptions {
  maxEntries?: number;
}

export interface ChatHistory {
  add(msg: ChatMessage): void;
  entries(): ChatMessage[];
  size(): number;
  clear(): void;
  subscribe(listener: () => void): () => void;
}

const DEFAULT_MAX_ENTRIES = 200;

export function createChatHistory(opts: ChatHistoryOptions = {}): ChatHistory {
  const maxEntries = opts.maxEntries ?? DEFAULT_MAX_ENTRIES;
  const buffer: ChatMessage[] = [];
  const listeners = new Set<() => void>();
  // Dedupe set — a re-broadcast / sync echo of an already-received id
  // is a no-op. Bounded by `maxEntries` because we evict oldest ids
  // alongside the buffer trim.
  const seenIds = new Set<string>();

  function notify() {
    for (const l of listeners) l();
  }

  return {
    add(msg) {
      if (!msg.id || seenIds.has(msg.id)) return;
      seenIds.add(msg.id);
      buffer.push(msg);
      while (buffer.length > maxEntries) {
        const evicted = buffer.shift();
        if (evicted) seenIds.delete(evicted.id);
      }
      notify();
    },
    entries() {
      return buffer.slice();
    },
    size: () => buffer.length,
    clear() {
      if (buffer.length === 0) return;
      buffer.length = 0;
      seenIds.clear();
      notify();
    },
    subscribe(listener) {
      listeners.add(listener);
      return () => listeners.delete(listener);
    },
  };
}

/**
 * Phase 119 — should this Spectator render the message? GM-only
 * messages from anyone are dropped; everything else passes through.
 * The GM never filters — they see everything (GM-only messages are
 * private notes / whispers the GM is meant to see).
 */
export function spectatorShouldRenderChat(msg: ChatMessage): boolean {
  return msg.visibility !== 'gm-only';
}
